# This workflow will run Pytest on pull requests to ensure that tests pass before merging.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#running-tests-with-pytest

name: Run Pytest

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv pip install -r requirements.txt --system
      - name: Run pytest
        run: pytest
